:angular_issues_url: xref:module-federation-v2/concepts/webcomponents/expose-content-as-webcomponent.adoc#angular_issues
:angular-webcomponents_url: xref:module-federation-v2/onecx/angular-webcomponents.adoc#onecx-angular-webcomponents

[#content-exposed-using-webcomponent-method]
=== Content Exposed Using Webcomponent Method

{angular-webcomponents_url}[Loading mechanism for modules and Remote Components exposed using Webcomponent method] requires that content is adapted to using Web Components Custom Elements. For both content types, bootstrapping logic needs to register a Custom Element in the Custom Elements Registry.

NOTE: For Angular-based content, apart from Custom Element registration, it is also required to cover a few Angular-related issues. For more information on those issues, please refer {angular_issues_url}[here].

It is recommended to use the {angular-webcomponents_url}[@onecx/angular-webcomponents] library to bootstrap Microfrontend's content using its exposed methods. This library will be used in the examples throughout this document.

.Navigation
[cols="1,1"]
|===
| xref:module-federation-v2/onecx/microfrontend-bootstrapping/angular-expose-method.adoc[← Previous: Content Exposed Using Angular Method]
| xref:./index.adoc[Next: Back to Microfrontend Bootstrapping →]
|===
