:mfe-loading_url: xref:../../concepts/content-loading.adoc

[#microfrontend-content-bootstrapping-explained]
== Microfrontend Content Bootstrapping Explained
{mfe-loading_url}[Microfrontend content loading] is an action triggered by the route change (Shell Application's responsibility of loading modules) or by the Slot Component display (Slot Component's responsibility of loading Remote Components). During this action, Microfrontend's content, exposed via remote entry file, is loaded and bootstrapped using the provided file in xref:../microfrontend-configuration.adoc[Webpack configuration].

Depending on the content type and chosen expose method, different adjustments have to be made to ensure correct content bootstrapping.

* xref:angular-expose-method.adoc[Content Exposed Using Angular Method]
* xref:webcomponent-expose-method.adoc[Content Exposed Using Webcomponent Method]

.Navigation
[cols="1,1"]
|===
| xref:./index.adoc[← Previous: Microfrontend Bootstrapping]
| xref:./angular-expose-method.adoc[Next: Content Exposed Using Angular Method →]
|===