[#module-federation-loading]
= Module Federation Loading Explained

Independent of the content type and expose method, the OneCX platform loads exposed content using **Module Federation**.

During this process, the exposed content is loaded using the file specified in the webpack configuration for the respective content.
As this example uses Webpack, this configuration is specified in the `webpack.config.js` file.

.Example
[source, javascript]
---
const config = withModuleFederationPlugin({
  name: 'my-application-ui',
  filename: 'remoteEntry.js',
  exposes: {
    './MyDefaultModule': './src/main.ts',
    './MyRemoteComponent': './src/app/remotes/my-comp/my-comp.component.main.ts'
  },
  ...
})    
---
== Notes

* `MyDefaultModule` - The file is used for module loading.
* `MyRemoteComponent` - The file is used for remote component loading.

== Loading process

Files defined in the configuration are used to load the exposed content. These files should contain all the required setup to display content.

The implementation inside these files depends on the chosen expose method.
